# Generated by Django 2.2 on 2020-09-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='用户昵称'),
        ),
    ]
