# Generated by Django 2.2 on 2020-10-14 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_auto_20201014_1234'),
        ('users', '0004_auto_20201013_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credit',
            name='number',
            field=models.IntegerField(default=0, help_text='如果是扣除积分则需要设置积分为负数，如果消费10积分，则填写-10，<br>如果是添加积分则需要设置积分为正数，如果获得10积分，则填写10。', verbose_name='积分数量'),
        ),
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='名称/标题')),
                ('orders', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updateed_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('last_time', models.DateTimeField(verbose_name='最近一次购买时间')),
                ('has_time', models.DateTimeField(verbose_name='购买过期时间')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course2users', to='courses.Course', verbose_name='课程名称')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2courses', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户课程购买记录',
                'verbose_name_plural': '用户课程购买记录',
                'db_table': 'ly_user_course',
            },
        ),
    ]
