# Generated by Django 2.2 on 2020-10-11 19:03

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0007_auto_20201012_0303'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='名称/标题')),
                ('orders', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updateed_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('coupon_type', models.SmallIntegerField(choices=[(1, '减免优惠'), (2, '折扣优惠')], default=1, help_text='优惠类型分2种:<br>1. 减免优惠,需要设置优惠券使用条件,用户使用过程中, 针对订单进行减免.<br>2. 折扣优惠, 只针对指定的商品有效, 需要设置优惠券关联的商品,否则发放以后用户无法使用.', verbose_name='优惠类型')),
                ('duration', models.IntegerField(default=7, help_text='优惠券有效期(天), 默认7天有效.', verbose_name='优惠券有效期')),
                ('condition', models.IntegerField(blank=True, default=0, verbose_name='优惠券使用的价格条件')),
                ('number', models.IntegerField(default=100, verbose_name='发放数量')),
                ('method', models.SmallIntegerField(choices=[(1, '系统赠送'), (2, '用户中心领取'), (3, '注册赠送')], default=1, verbose_name='发放方式')),
                ('sale', models.TextField(help_text='\n        *号开头表示折扣优惠，例如*0.82表示针对商品进行八二折；<br>\n        -号开头表示减免优惠, 例如-10表示在总价基础上减免10元<br>   \n        ', verbose_name='优惠公式')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_coupon', to='courses.Course', verbose_name='关联课程')),
            ],
            options={
                'verbose_name': '优惠券类型',
                'verbose_name_plural': '优惠券类型',
                'db_table': 'ly_coupon',
            },
        ),
        migrations.CreateModel(
            name='UserCoupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=150, null=True, verbose_name='名称/标题')),
                ('orders', models.IntegerField(default=0, verbose_name='显示顺序')),
                ('is_show', models.BooleanField(default=True, verbose_name='是否上架')),
                ('is_delete', models.BooleanField(default=False, verbose_name='逻辑删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updateed_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('start_time', models.DateTimeField(default=datetime.datetime(2020, 10, 11, 19, 3, 3, 851545, tzinfo=utc), verbose_name='优惠券的启用时间')),
                ('is_use', models.BooleanField(default=False, verbose_name='优惠券是否使用过')),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='coupon.Coupon', verbose_name='优惠券')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户的优惠券',
                'verbose_name_plural': '用户的优惠券',
                'db_table': 'ly_user_coupon',
            },
        ),
    ]
