# Generated by Django 2.2 on 2020-09-28 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_auto_20200928_0916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseexpire',
            name='expire',
        ),
        migrations.AlterField(
            model_name='courseexpire',
            name='name',
            field=models.CharField(blank=True, default=None, help_text='例如: 1个月有效', max_length=150, null=True, verbose_name='课程有效期(天)'),
        ),
    ]
